version: "3"
services:
  serv:
    container_name: javacorrect-serv
    build: "./JavaCorrect-Serveur"
  db:
    container_name: javacorrect-db
    build: "./JavaCorrectDatabase"
    ports:
      - "3306:3306"

